# Generated by Django 3.1.1 on 2020-09-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.TimeField()),
                ('max_attendees', models.IntegerField()),
                ('state', models.CharField(choices=[('Y', 'Activo'), ('N', 'Inactivo')], default='Y', max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.CharField(default='N', max_length=1, null=True)),
                ('attended_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('fever', models.CharField(default='N', max_length=1, null=True)),
                ('cough', models.CharField(default='N', max_length=1, null=True)),
                ('headache', models.CharField(default='N', max_length=1, null=True)),
                ('sore_throat', models.CharField(default='N', max_length=1, null=True)),
                ('general_discomfort', models.CharField(default='N', max_length=1, null=True)),
                ('respiratory_difficulty', models.CharField(default='N', max_length=1, null=True)),
                ('adinamia', models.CharField(default='N', max_length=1, null=True)),
                ('nasal_secretions', models.CharField(default='N', max_length=1, null=True)),
                ('diarrhea', models.CharField(default='N', max_length=1, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('close_person', models.CharField(default='N', max_length=1, null=True)),
                ('washed', models.CharField(default='N', max_length=1, null=True)),
                ('agree', models.CharField(default='N', max_length=1, null=True)),
                ('is_servant', models.CharField(choices=[('Y', 'Activo'), ('N', 'Inactivo')], default='N', max_length=1, null=True)),
                ('was_returned', models.CharField(choices=[('Y', 'Activo'), ('N', 'Inactivo')], default='N', max_length=1, null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assist_control.assistant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assist_control.service')),
            ],
        ),
    ]
